interface SwipContent {
  id: string;
  type: 'video' | 'card';
  title: string;
  description: string;
  category: string;
  thumbnail: string;
  duration?: string;
  likes: number;
  views: number;
  isWishlisted: boolean;
  isEnrolled: boolean;
  instructor: string;
  tags: string[];
  videoUrl?: string;
  noteId?: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  lastUpdated: string;
}

export const sampleContent: SwipContent[] = [
  {
    id: "machine-learning-intro",
    type: "video",
    title: "Introduction to Machine Learning",
    description: "Learn the fundamentals of machine learning and AI in this comprehensive tutorial.",
    category: "Computer Science",
    thumbnail: "/src/assets/topics/machine-learning.jpg",
    duration: "4:15",
    likes: 1200,
    views: 5000,
    isWishlisted: false,
    isEnrolled: false,
    instructor: "Dr. Sarah Chen",
    tags: ["AI", "Machine Learning", "Data Science"],
    videoUrl: "https://example.com/videos/ml-intro",
    noteId: "ml-basics",
    difficulty: "Beginner",
    lastUpdated: "2025-09-20"
  },
  {
    id: "quantum-mechanics",
    type: "video",
    title: "Understanding Quantum Mechanics",
    description: "Explore the fascinating world of quantum physics and its applications.",
    category: "Physics",
    thumbnail: "/src/assets/topics/quantum-mechanics.jpg",
    duration: "5:30",
    likes: 850,
    views: 3200,
    isWishlisted: true,
    isEnrolled: false,
    instructor: "Prof. Michael Feynman",
    tags: ["Physics", "Quantum", "Modern Physics"],
    videoUrl: "https://example.com/videos/quantum",
    noteId: "quantum-basics",
    difficulty: "Advanced",
    lastUpdated: "2025-09-19"
  },
  {
    id: "linear-algebra",
    type: "card",
    title: "Linear Algebra Essentials",
    description: "Master the fundamental concepts of linear algebra with practical examples.",
    category: "Mathematics",
    thumbnail: "/src/assets/topics/linear-algebra.jpg",
    likes: 950,
    views: 4200,
    isWishlisted: false,
    isEnrolled: true,
    instructor: "Prof. Emma Matrix",
    tags: ["Mathematics", "Linear Algebra", "Vectors"],
    noteId: "linear-algebra-101",
    difficulty: "Intermediate",
    lastUpdated: "2025-09-18"
  },
  {
    id: "renaissance-art",
    type: "video",
    title: "The Renaissance Period",
    description: "Journey through the golden age of art and culture in Europe.",
    category: "Art History",
    thumbnail: "/src/assets/topics/renaissance-art.jpg",
    duration: "6:45",
    likes: 780,
    views: 2900,
    isWishlisted: false,
    isEnrolled: false,
    instructor: "Dr. Isabella Arte",
    tags: ["Art", "History", "Renaissance"],
    videoUrl: "https://example.com/videos/renaissance",
    noteId: "renaissance-intro",
    difficulty: "Beginner",
    lastUpdated: "2025-09-17"
  },
  {
    id: "digital-marketing",
    type: "card",
    title: "Digital Marketing Strategies",
    description: "Learn modern digital marketing techniques and strategies for business growth.",
    category: "Marketing",
    thumbnail: "/src/assets/topics/digital-marketing.jpg",
    likes: 1100,
    views: 4800,
    isWishlisted: true,
    isEnrolled: true,
    instructor: "Alex Social",
    tags: ["Marketing", "Digital", "Business"],
    noteId: "digital-marketing-guide",
    difficulty: "Intermediate",
    lastUpdated: "2025-09-16"
  },
  {
    id: "molecular-biology",
    type: "video",
    title: "DNA and RNA Structure",
    description: "Understand the building blocks of life through molecular biology.",
    category: "Biology",
    thumbnail: "/src/assets/topics/molecular-biology.jpg",
    duration: "7:20",
    likes: 920,
    views: 3600,
    isWishlisted: false,
    isEnrolled: true,
    instructor: "Dr. Gene Splitter",
    tags: ["Biology", "Genetics", "Molecular"],
    videoUrl: "https://example.com/videos/dna-rna",
    noteId: "molecular-bio-basics",
    difficulty: "Advanced",
    lastUpdated: "2025-09-15"
  },
  {
    id: "react-advanced",
    type: "card",
    title: "Advanced React Patterns",
    description: "Deep dive into advanced React patterns and performance optimization.",
    category: "Programming",
    thumbnail: "/src/assets/courses/react.jpg",
    likes: 1500,
    views: 6200,
    isWishlisted: true,
    isEnrolled: false,
    instructor: "Jennifer Dev",
    tags: ["React", "JavaScript", "Web Development"],
    noteId: "react-patterns",
    difficulty: "Advanced",
    lastUpdated: "2025-09-14"
  },
  {
    id: "climate-change",
    type: "video",
    title: "Climate Change Impact",
    description: "Analyze the global impact of climate change and potential solutions.",
    category: "Environmental Science",
    thumbnail: "/src/assets/topics/climate.jpg",
    duration: "8:15",
    likes: 2100,
    views: 8900,
    isWishlisted: false,
    isEnrolled: true,
    instructor: "Dr. Earth Saver",
    tags: ["Environment", "Climate", "Science"],
    videoUrl: "https://example.com/videos/climate",
    noteId: "climate-analysis",
    difficulty: "Intermediate",
    lastUpdated: "2025-09-13"
  },
  {
    id: "psychology-101",
    type: "card",
    title: "Introduction to Psychology",
    description: "Explore the fundamentals of human behavior and mental processes.",
    category: "Psychology",
    thumbnail: "/src/assets/courses/psychology.jpg",
    likes: 1800,
    views: 7500,
    isWishlisted: true,
    isEnrolled: true,
    instructor: "Dr. Mind Reader",
    tags: ["Psychology", "Behavior", "Mental Health"],
    noteId: "psych-basics",
    difficulty: "Beginner",
    lastUpdated: "2025-09-12"
  },
  {
    id: "blockchain-tech",
    type: "video",
    title: "Blockchain Technology",
    description: "Understanding blockchain fundamentals and cryptocurrency.",
    category: "Technology",
    thumbnail: "/src/assets/courses/blockchain.jpg",
    duration: "5:45",
    likes: 1600,
    views: 6800,
    isWishlisted: false,
    isEnrolled: false,
    instructor: "Crypto Master",
    tags: ["Blockchain", "Cryptocurrency", "Technology"],
    videoUrl: "https://example.com/videos/blockchain",
    noteId: "blockchain-101",
    difficulty: "Intermediate",
    lastUpdated: "2025-09-11"
  },
  {
    id: "creative-writing",
    type: "card",
    title: "Creative Writing Workshop",
    description: "Master the art of storytelling and creative writing.",
    category: "Literature",
    thumbnail: "/src/assets/courses/writing.jpg",
    likes: 950,
    views: 4100,
    isWishlisted: true,
    isEnrolled: true,
    instructor: "Word Smith",
    tags: ["Writing", "Literature", "Creativity"],
    noteId: "writing-guide",
    difficulty: "Beginner",
    lastUpdated: "2025-09-10"
  },
  {
    id: "data-structures",
    type: "video",
    title: "Advanced Data Structures",
    description: "Deep dive into complex data structures and algorithms.",
    category: "Computer Science",
    thumbnail: "/src/assets/courses/data-structures.jpg",
    duration: "6:30",
    likes: 2200,
    views: 9100,
    isWishlisted: true,
    isEnrolled: false,
    instructor: "Prof. Algorithm",
    tags: ["Data Structures", "Algorithms", "Programming"],
    videoUrl: "https://example.com/videos/data-structures",
    noteId: "ds-advanced",
    difficulty: "Advanced",
    lastUpdated: "2025-09-09"
  },
  {
    id: "modern-architecture",
    type: "card",
    title: "Modern Architecture",
    description: "Explore contemporary architectural designs and principles.",
    category: "Architecture",
    thumbnail: "/src/assets/courses/architecture.jpg",
    likes: 1300,
    views: 5500,
    isWishlisted: false,
    isEnrolled: true,
    instructor: "Design Master",
    tags: ["Architecture", "Design", "Modern"],
    noteId: "architecture-principles",
    difficulty: "Intermediate",
    lastUpdated: "2025-09-08"
  },
  {
    id: "financial-planning",
    type: "video",
    title: "Personal Finance Essentials",
    description: "Learn effective financial planning and investment strategies.",
    category: "Finance",
    thumbnail: "/src/assets/courses/finance.jpg",
    duration: "7:15",
    likes: 1900,
    views: 7800,
    isWishlisted: true,
    isEnrolled: true,
    instructor: "Money Wise",
    tags: ["Finance", "Investment", "Planning"],
    videoUrl: "https://example.com/videos/finance",
    noteId: "finance-101",
    difficulty: "Beginner",
    lastUpdated: "2025-09-07"
  },
  {
    id: "neuroscience",
    type: "card",
    title: "Introduction to Neuroscience",
    description: "Discover the fascinating world of the human brain.",
    category: "Neuroscience",
    thumbnail: "/src/assets/courses/brain.jpg",
    likes: 1700,
    views: 6900,
    isWishlisted: false,
    isEnrolled: false,
    instructor: "Dr. Brain Wave",
    tags: ["Neuroscience", "Biology", "Psychology"],
    noteId: "neuro-intro",
    difficulty: "Advanced",
    lastUpdated: "2025-09-06"
  }
];

export default sampleContent;